#!/usr/bin/env bash

#
# This pre-commit hook lint-fixes all altered js files and adds them to git.
#

printf "   🧹 Beginning pre-commit...\n"

starting_dir=$(pwd)
root_dir=`git rev-parse --show-toplevel`

# enter the directory where ./node_modules is or eslint will complain that it
# cannot find its plugins
cd $root_dir

altered_js_files=`git diff HEAD --cached --name-only --diff-filter=ACM | grep .js$ | grep -v .eslintrc.js$`

if ! [ -z "$altered_js_files" ]
then
  printf "   🧹 linting js files with --fix...\n"
  # Manually clean up js files. If it fails, use || to ignore the error (we don't
  # want to block the commit). Let lint print its warnings
  $root_dir/node_modules/.bin/eslint --fix $altered_js_files || printf ""

  printf "   🍵 Adding linted files to git \n"
  for file in $altered_js_files
  do
    git add $file
  done
fi

# return to previous directory
cd $starting_dir
